version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    commit:
      jobs:
        - build-and-test
    weekly:
      triggers:
        - schedule:
            cron: "0 0 * * 1"
            filters:
              branches:
                only:
                - master
      jobs:
        - build-and-test
